"use client";
import { useEffect, useState } from "react";
import { generateAIResponse } from "../lib/ai";
import { getUsername, getCurrentUser, readJSON, writeJSON, STORAGE_KEYS } from "../lib/storage";
import { api } from "../lib/api";

const prompts = ["Improve my startup idea", "Analyze my startup idea", "Find my target audience", "Suggest a business model", "How can I monetize this idea?", "Suggest features", "Find possible problems", "Suggest a startup name", "Give me a launch plan", "Find risks and solutions"];

export default function AIChat({ context }) {
  const [messages, setMessages] = useState([]); const [input, setInput] = useState(""); const [typing, setTyping] = useState(false);
  useEffect(() => { const stored = readJSON(STORAGE_KEYS.aiChat, {}); const history = Array.isArray(stored?.[getUsername()]) ? stored[getUsername()] : []; setMessages(history.length ? history : [{ role: "ai", message: context ? `I’m ready to work on ${context.title || context.name}. Ask me to improve it, find its risks, or plan the launch.` : "I’m ready to help you turn a rough thought into a sharper startup concept. What are you exploring?", timestamp: new Date().toISOString() }]); }, [context]);
  const save = (next) => { setMessages(next); const stored = readJSON(STORAGE_KEYS.aiChat, {}); writeJSON(STORAGE_KEYS.aiChat, { ...(stored && !Array.isArray(stored) ? stored : {}), [getUsername()]: next.slice(-80) }); };
  const send = async (value = input) => { const text = value.trim(); if (!text || typing) return; const next = [...messages, { role: "user", message: text, timestamp: new Date().toISOString() }]; save(next); setInput(""); setTyping(true); try { const result = await api.post("/ai/chat", { message: text, ideaId: context?.id }); save([...next, { role: "ai", message: result.response, timestamp: new Date().toISOString() }]); } catch { save([...next, { role: "ai", message: generateAIResponse(text, context), timestamp: new Date().toISOString() }]); } finally { setTyping(false); } };
  return <section className="ai-workspace"><aside className="ai-rail"><div className="ai-identity"><span className="ai-avatar">✦</span><div><strong>IDEALAUNCH AI</strong><small>Startup copilot · Online</small></div><span className="status-dot" /></div><p className="ai-rail-copy">Turn early sparks into sharper opportunities, stronger business models, and a confident next move.</p><span className="section-label">Quick suggestions</span><div className="quick-prompts">{prompts.map((prompt) => <button key={prompt} onClick={() => send(prompt)}><span>✦</span>{prompt}</button>)}</div><button className="clear-chat" onClick={() => save([])}>Clear chat history</button></aside><div className="ai-chat-panel"><div className="chat-messages">{messages.map((item, index) => <article className={`chat-message ${item.role === "user" ? "user-message" : "ai-message"}`} key={`${item.timestamp}-${index}`}><span className={`ai-avatar ${item.role === "user" ? "user-avatar" : ""}`}>{item.role === "user" ? (getCurrentUser().fullName.charAt(0) || "U") : "✦"}</span><div className="chat-bubble"><div className="ai-message-text">{item.message}</div><small>{item.role === "user" ? "You" : "IDEALAUNCH AI"} · {new Date(item.timestamp).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</small></div></article>)}</div><div className="typing-indicator" hidden={!typing}>IDEALAUNCH AI is thinking... <i /><i /><i /></div><form className="chat-form" onSubmit={(event) => { event.preventDefault(); send(); }}><textarea value={input} onChange={(event) => setInput(event.target.value)} placeholder="Ask IDEALAUNCH AI anything..." /><button className="button button-primary" type="submit">Send <span>→</span></button></form><p className="ai-disclaimer">Frontend demo engine. Responses are generated locally in your browser.</p></div></section>;
}
