const bcrypt = require("bcryptjs");
const jwt = require("jsonwebtoken");
const users = require("../data/users");
const safeUser = (user) => ({ id: user.id, fullName: user.fullName, username: user.username, email: user.email, createdAt: user.createdAt });
function tokenFor(user) { return jwt.sign({ userId: user.id }, process.env.JWT_SECRET, { expiresIn: "7d" }); }
function validateEmail(email) { return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email); }
async function register(req, res) { const { fullName, username, email, password, confirmPassword } = req.body || {}; if (!fullName || !username || !email || !password || !confirmPassword) return res.status(400).json({ success: false, message: "Complete all required fields" }); if (users.some((user) => user.username.toLowerCase() === username.toLowerCase())) return res.status(409).json({ success: false, message: "Username already exists" }); if (!validateEmail(email)) return res.status(400).json({ success: false, message: "Enter a valid email address" }); if (users.some((user) => user.email.toLowerCase() === email.toLowerCase())) return res.status(409).json({ success: false, message: "An account with this email already exists" }); if (password.length < 6) return res.status(400).json({ success: false, message: "Password must be at least 6 characters" }); if (password !== confirmPassword) return res.status(400).json({ success: false, message: "Passwords do not match" }); const user = { id: `user-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`, fullName: fullName.trim(), username: username.trim(), email: email.toLowerCase().trim(), passwordHash: await bcrypt.hash(password, 10), createdAt: new Date().toISOString().slice(0, 10), favourites: [], recentlyViewed: [] }; users.push(user); res.status(201).json({ success: true, user: safeUser(user), token: tokenFor(user) }); }
async function login(req, res) { const { username, password } = req.body || {}; const user = users.find((item) => item.username.toLowerCase() === String(username || "").toLowerCase() || item.email.toLowerCase() === String(username || "").toLowerCase()); if (!user || !(await bcrypt.compare(password || "", user.passwordHash))) return res.status(401).json({ success: false, message: "Invalid username or password" }); res.json({ success: true, user: safeUser(user), token: tokenFor(user) }); }
function me(req, res) { res.json({ success: true, user: safeUser(req.user) }); }
function logout(req, res) { res.json({ success: true, message: "Logged out successfully" }); }
module.exports = { register, login, me, logout, safeUser };
