const ideas = require("../data/ideas");
const users = require("../data/users");
const userIdeas = [];
const allIdeas = () => [...ideas, ...userIdeas];
const titleOf = (idea) => idea.title || idea.name;
function list(req, res) { const { search = "", category = "all", sort = "featured" } = req.query; let result = allIdeas().filter((idea) => { const text = [titleOf(idea), idea.description, idea.category, idea.audience || idea.targetAudience, ...(idea.tags || [])].join(" ").toLowerCase(); return text.includes(String(search).toLowerCase()) && (category.toLowerCase() === "all" || idea.category.toLowerCase() === category.toLowerCase()); }); if (sort === "rating") result.sort((a, b) => (b.rating || 0) - (a.rating || 0)); if (sort === "newest") result.reverse(); if (sort === "az") result.sort((a, b) => titleOf(a).localeCompare(titleOf(b))); res.json({ success: true, ideas: result }); }
function getOne(req, res) { const idea = allIdeas().find((item) => item.id === req.params.id); if (!idea) return res.status(404).json({ success: false, message: "Idea not found" }); res.json({ success: true, idea }); }
function create(req, res) { const body = req.body || {}; const required = [body.name || body.title, body.description, body.category, body.problem, body.solution, body.targetAudience, body.businessModel]; if (required.some((value) => !String(value || "").trim())) return res.status(400).json({ success: false, message: "Complete all required fields before submitting your idea" }); const idea = { ...body, id: `user-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`, name: body.name || body.title, title: body.title || body.name, date: new Date().toISOString().slice(0, 10), rating: 0, createdBy: req.user.username, createdByUserId: req.user.id, isUserSubmitted: true, features: Array.isArray(body.features) ? body.features : [], tags: Array.isArray(body.tags) ? body.tags : [] }; userIdeas.unshift(idea); res.status(201).json({ success: true, idea }); }
function update(req, res) { const index = userIdeas.findIndex((idea) => idea.id === req.params.id); if (index < 0) return res.status(ideas.some((idea) => idea.id === req.params.id) ? 403 : 404).json({ success: false, message: ideas.some((idea) => idea.id === req.params.id) ? "You are not allowed to perform this action" : "Idea not found" }); if (userIdeas[index].createdByUserId !== req.user.id) return res.status(403).json({ success: false, message: "You are not allowed to perform this action" }); userIdeas[index] = { ...userIdeas[index], ...req.body, id: userIdeas[index].id, createdBy: userIdeas[index].createdBy, createdByUserId: userIdeas[index].createdByUserId, isUserSubmitted: true }; res.json({ success: true, idea: userIdeas[index] }); }
function remove(req, res) { const index = userIdeas.findIndex((idea) => idea.id === req.params.id); if (index < 0) return res.status(ideas.some((idea) => idea.id === req.params.id) ? 403 : 404).json({ success: false, message: ideas.some((idea) => idea.id === req.params.id) ? "You are not allowed to perform this action" : "Idea not found" }); if (userIdeas[index].createdByUserId !== req.user.id) return res.status(403).json({ success: false, message: "You are not allowed to perform this action" }); userIdeas.splice(index, 1); res.json({ success: true, message: "Idea deleted" }); }
module.exports = { list, getOne, create, update, remove, allIdeas, userIdeas, users };
